version: "3"
services:

  postgres:
    image: postgres:9.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=TCrGaanoC2s7gT

  zookeeper:
    container_name: zookeeper
    image: znly/zookeeper:3.4.8
    environment:
      - ZOO_ID=1
      - ZOO_SERVERS=zookeeper

  overlord:
    image: gcr.io/npav-172917/druid:0.10.0-1
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - 8090:8090
    command:
      - overlord

  coordinator:
    image: gcr.io/npav-172917/druid:0.10.0-1
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    command:
      - coordinator


  middlemanager:
    image: gcr.io/npav-172917/druid:0.10.0-1
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    command:
      - middleManager

  historical:
    image: gcr.io/npav-172917/druid:0.10.0-1
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
      - DRUID_MAX_DIRECTMEM_SIZE=1500m
    command:
      - historical

  broker:
    image: gcr.io/npav-172917/druid:0.10.0-1
    environment:
      - DRUID_XMX=3g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=800m
      - DRUID_NEWSIZE=500m
      - DRUID_MAX_DIRECTMEM_SIZE=1500m
    deploy:
      placement:
        constraints:
          - node.role == manager
    command:
      - broker
