version: "3"
services:

  interlock:
    image: ehazlett/interlock:1.4.1
    command: -D run  -c /etc/interlock/config.toml
    tty: true
    ports:
        - 8080
    environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "unix:///var/run/docker.sock"
            # TLSCACert = "/etc/docker/ca.pem"
            # TLSCert = "/etc/docker/server.pem"
            # TLSKey = "/etc/docker/server-key.pem"
            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/nginx/nginx.conf"
            PidPath = "/var/run/nginx.pid"
            TemplatePath = ""
            MaxConn = 1024
            Port = 80
    volumes:
        - /etc/docker:/etc/docker:ro
        - /var/run/docker.sock:/var/run/docker.sock

    deploy:
      placement:
        constraints:
          - node.role == manager

  nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=nginx"
    deploy:
      placement:
        constraints:
          - node.role == manager

  postgres:
    image: postgres:9.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=TCrGaanoC2s7gT

  zookeeper:
    container_name: zookeeper
    image: znly/zookeeper:3.4.8
    environment:
      - ZOO_ID=1
      - ZOO_SERVERS=zookeeper

  overlord:
    image: gcr.io/npav-172917/druid:0.10.0-1
    hostname: overloard
    labels:
        - "interlock.hostname=test"
        - "interlock.domain=aodtest.com"
        - "interlock.port=8090"
        - "interlock.network=druid_default"
        - "interlock.context_root=/overlord"
        - "interlock.context_root_rewrite=true"
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - 8090
    command:
      - overlord

  coordinator:
    image: gcr.io/npav-172917/druid:0.10.0-1
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    command:
      - coordinator


  middlemanager:
    image: gcr.io/npav-172917/druid:0.10.0-1
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    command:
      - middleManager

  historical:
    image: gcr.io/npav-172917/druid:0.10.0-1
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
      - DRUID_MAX_DIRECTMEM_SIZE=1500m
    command:
      - historical

  broker:
    image: gcr.io/npav-172917/druid:0.10.0-1
    environment:
      - DRUID_XMX=3g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=800m
      - DRUID_NEWSIZE=500m
      - DRUID_MAX_DIRECTMEM_SIZE=1500m
    deploy:
      placement:
        constraints:
          - node.role == manager
    command:
      - broker

  pithos:
    image: gcr.io/npav-172917/pithos:latest
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
    volumes:
      - /var/lib/data/pithos:/pithos/data
  cassandra:
    image: cassandra:2.1
